### ISSUE TITLE
Database error, when trying to signUp or signIn

### ISSUE THREAD

**Issue by lunairsappsPerso** [evanfreeze/read-rate-remix#4]
Hi, there is a database error, when the user tries to sign In or sin Up.

URL: [https://www.readrate.app/login?redirectTo=%2Fnow-reading](url)

The error message
![image](https://user-images.githubusercontent.com/108534413/182042357-58f82d04-3584-4882-9e4e-58f2ee69024c.png)

**Comment by evanfreeze** [comment]
Hey @lunarisapps — this should be fixed now. Can you try again and let me know?
